#if !canImport(ObjectiveC)
import XCTest

extension PBXGlobalIDTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXGlobalIDTests = [
        ("testIDGeneration", testIDGeneration),
    ]
}

extension XcodeProjectTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XcodeProjectTests = [
        ("testAggregateTarget", testAggregateTarget),
        ("testPrivateProjectFolder", testPrivateProjectFolder),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PBXGlobalIDTests.__allTests__PBXGlobalIDTests),
        testCase(XcodeProjectTests.__allTests__XcodeProjectTests),
    ]
}
#endif
